from typing import Protocol

from entities.chat import ChatMessageTrace, ChatObservation, ChatSession, ChatSessionTrace, RetrievedChunk


class KnowledgeRetriever(Protocol):
    async def retrieve(self, query: str, limit: int = 4) -> list[RetrievedChunk]: ...


class SessionRepository(Protocol):
    async def get_or_create(self, session_id: str | None) -> ChatSession: ...
    async def save(self, session: ChatSession) -> None: ...


class ObservationRepository(Protocol):
    async def save(self, observation: ChatObservation) -> None: ...
    async def list_recent(self, limit: int = 100) -> list[ChatObservation]: ...
    async def add_feedback(self, observation_id: str, correctness: str, note: str | None = None) -> None: ...


class ChatTraceRepository(Protocol):
    async def save_session(self, session: ChatSessionTrace) -> None: ...
    async def save_message(self, message: ChatMessageTrace) -> None: ...
    async def list_sessions(self, limit: int = 100) -> list[ChatSessionTrace]: ...
    async def list_messages(self, session_id: str, limit: int = 100) -> list[ChatMessageTrace]: ...
    async def add_feedback(self, message_id: str, correctness: str, note: str | None = None) -> None: ...
